### ISSUE TITLE
Login ...

### ISSUE THREAD

**Issue by breaup** [Itsyuka/CommunityBanBECPlugin#1]
Love the idea but Any ideas why I can't login ? Does not say wrong username or password. Tried on chrome and IE 11 . 

I activated my account from the email too .... clicked the im not a robot ... the page just seem to refresh it self

**Comment by Itsyuka** [comment]
You're account is activated and seems to be working fine.

**Comment by breaup** [comment]
Ill clear my cache and try it again

**Comment by breaup** [comment]
After clearing my cache now when I hit the login button I get: 
 You must login to access this area. 

lol fun times

**Comment by Itsyuka** [comment]
Yea I didn't get the time to add in "User/Email or password doesn't match or exist"

**Comment by breaup** [comment]
cool ill do a password reset and try her again. Thanks
